version: '3'
services:
  app-api:
    # 起動イメージ
    image: node:18.15.0-buster-slim
    # 環境変数
    environment:
      - DEBUG=app:*
    tty: true
    # ホスト側のポート：コンテナのポート
    ports:
      - '3000:3000'
    # ホスト側のsrcをコンテナのappにマウント
    volumes:
      - ./src:/app
    # 起動時のカレントフォルダ
    working_dir: /app
    # 起動後に実行するコマンド
    command: sh -c 'npx tsc; npm run dev'
  db:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: react_express_sample_development
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
volumes:
  db-store: