name: ci
on:
  pull_request:
    branches:
      - master
      - main

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: write
    if: github.event_name  == 'pull_request'
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: install npm packagegs
        run: npm ci
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run lint | reviewdog -f=eslint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true
      - name: execute lint
        run: npm run lint
      - name: execute unit test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test
          working-directory: frontend
