name: ci
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: install npm packagegs
        run: npm ci
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: execute Lint
        run: npm run lint | reviewdog -f=eslint -reporter=github-pr-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on lint failure
        if: ${{ job.status == 'failure' }}
        uses: reviewdog/action-github-pr-review@v1.x
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          reporter: github-pr-review